### ISSUE TITLE
Unable to Perform Local Rename & Conversion Prior to Moving/Sorting on NAS

### ISSUE THREAD

**Issue by WalrusSwarm** [mdhiggins/sonarr-sma#39]
**Issue/Question:**
Is it possible to configure my autoProcess.ini file such that files are:   
Passed to Sonarr for Renaming --> Converted (locally Device1 ) --> Moved/Sorted (Device2 = NAS)  
Or Would I need a custom script?  

Current Configuration (2-devices):  
Device1 = Server Running Docker  
Device2 = NAS 

**Current Setup:**  

1. Completed Files are Passed to Sonarr for Renaming (Device1)  
2. --> Moved/Sorted to NAS (Device1 --> Device2)  
3. <--> Device1 Converts Files over the Network (Device1 <--Network Overhead--> Device2)  

**Problems:** 

1. Slow Due to Unnecessary local network traffic 
2. Writes files 3x to my NAS .mkv + m4v + qtfs. 

**Ideal Setup:**

1. Pass Completed Files to Sonarr for Renaming (Device1)
2. --> Convert Files Locally in Temporary Directory (Device1) 
3. --> Move & Sort (Device1 --> Device2)

**Comment by mdhiggins** [comment]
This is more of a Sonarr/Radarr limitation as there is no point event in custom script execution that allows you to make these changes before the file is moved

This however is the whole reason this script also includes post-downloader scripts so that before Radarr/Sonarr pick up the files the conversion can be performed.

The post downloader scripts are the deluge/qt/nzbget/sab/etc scripts for reference. I don't maintain individual containers for all these scripts but the docker mod can be used to add any of the linuxserver containers

https://github.com/mdhiggins/sma-mod

Additionally SMA can the `output-directory` and `temp-output` options that can be configured to have a working temporary directory for conversions

Hope that helps, happy to clarify any questions
