### ISSUE TITLE
Suggestion, auto-update on startup

### ISSUE THREAD

**Issue by RandomNinjaAtk** [mdhiggins/sonarr-sma#7]
So instead of having to push new image builds, to update the script every time, if a start-up script was used to pull down the latest code That would mean you only need to update the image to facilitate dependency changes.

**Comment by mdhiggins** [comment]
Yeah I've thought about implementing that but also didn't want to have someone have potentially unexpected changes to their setup caused by just restarting their docker container and have instead opted against it for that stability

That being said I've tackled most of the outstanding issues and major changes I've wanted to do to this script for a while now so I expect the frequency of updates to drop off soon so the need to update the container frequently should drop off as well

**Comment by RandomNinjaAtk** [comment]
You could make it an env variable to enable or disable it. So by default it's disabled, but if enabled perform a git pull. But I understand at some point which your approaching now. Not much will likely be expected to change frequently. I have some scripts I've written and have gotten to that threshold.

**Comment by mdhiggins** [comment]
cc7448da7f90d4eae542dfa18b2f5965382f179a

Added to radarr too

Rebuilding now

**Comment by mdhiggins** [comment]
Initial tests look good, appears to work fine

Feel free to close if you can confirm

**Comment by RandomNinjaAtk** [comment]
This looks to be working as expected! Makes updating much faster/easier ;)
